package com.bluezero.sinon.networks;

public class TyneAndWearNetwork {
	public static final int Id = 2;
	public static final String Name = "Tyne & Wear Metro";
	public static final String CultureCode = "en-GB";
	
	public static final String[] Stations = new String[] {
		"South Hylton",
		"Pallion",
		"Millfield",
		"University",
		"Park Lane",
		"Sunderland",
		"St. Peter's",
		"Stadium of Light",
		"Seaburn",
		"East Boldon",
		"Brockley Whins",
		"Fellgate",
		"South Shields",
		"Chichester",
		"Tyne Dock",
		"Simonside",
		"Bede",
		"Jarrow",
		"Hebburn",
		"Pelaw",
		"Heworth",
		"Felling",
		"Gateshead Stadium",
		"Gateshead",
		"Central",
		"Monument",
		"Haymarket",
		"Jesmond",
		"West Jesmond",
		"Ilford Road",
		"South Gosforth",
		"Regent Centre",
		"Wansbeck Road",
		"Fawdon",
		"Kingston Park",
		"Bank Foot",
		"Callerton Parkway",
		"Airport",
		"Longbenton",
		"Four Lane Ends",
		"Benton",
		"Palmersville",
		"Northumberland Park",
		"Shiremoor",
		"West Monkseaton",
		"Monkseaton",
		"Whitley Bay",
		"Cullercoats",
		"Tynemouth",
		"North Shields",
		"Meadow Well",
		"Percy Main",
		"Howdon",
		"Hadrian Road",
		"Wallsend",
		"Walkergate",
		"Chillingham Road",
		"Byker",
		"Manors",
		"St. James",
		"Gosforth",				
	};	 	 	 
}
